//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beeline.BeeZap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beeline.BeeZap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the backups will clear the Undo list and make all the changes permanent.  Do you want to permanently delete the backups?.
        /// </summary>
        internal static string DeleteBackupConfirmationText {
            get {
                return ResourceManager.GetString("DeleteBackupConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Backups?.
        /// </summary>
        internal static string DeleteBackupsConfirmationCaption {
            get {
                return ResourceManager.GetString("DeleteBackupsConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In Editor Failed.
        /// </summary>
        internal static string OpenInEditorFailedCaption {
            get {
                return ResourceManager.GetString("OpenInEditorFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A text editor has not been defined, or the defined editor could not be found, or the editor could not be started..
        /// </summary>
        internal static string OpenInEditorFailedText {
            get {
                return ResourceManager.GetString("OpenInEditorFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo All Changes?.
        /// </summary>
        internal static string UndoChangesConfirmationCaption {
            get {
                return ResourceManager.GetString("UndoChangesConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to undo all the changes?.
        /// </summary>
        internal static string UndoChangesConfirmationText {
            get {
                return ResourceManager.GetString("UndoChangesConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while restoring the backups.
        /// </summary>
        internal static string UndoChangesFailedCaption {
            get {
                return ResourceManager.GetString("UndoChangesFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A changed file could not be restored from backup.  Would you like to continue restoring the remaining backups?.
        /// </summary>
        internal static string UndoChangesFailedText {
            get {
                return ResourceManager.GetString("UndoChangesFailedText", resourceCulture);
            }
        }
    }
}
